config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "schedules#index"
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
##
# A Schedule instance represents a specific gliders scheduled reservations for a
# day.  The state held by an instace are the gliders name, the reporesented day
# and time slots.  Reservations for a glider are indicated by a name (any string)
# existing in a particular time slot.

class Schedule < ApplicationRecord

  @@managed_gliders = ['N2905H (2-33)','N2689H (2-33)','N820SB (L-23)','N747S (1-26)','N7643 (1-34)', 'Tow Only', 'Instructor']
  @@managed_time_slots = [
      :s0800, :s0830, :s0900, :s0930, :s1000, :s1030, :s1100, :s1130, :s1200,
      :s1230, :s1300, :s1330, :s1400, :s1430, :s1500, :s1530, :s1600, :s1630
     ]

  def self.managed_gliders
    @@managed_gliders
  end
  def self.managed_time_slots
    @@managed_time_slots
  end


  def self.schedule_for_day(day)
    existing_schedules = where(:day => day)
    if existing_schedules.empty?
      self.blank_day(day)
    else
      merge_slots(blank_day(day), existing_schedules)
    end
  end

  private

      # I should probably make a new constructor that takes a glider name
      # and simplify this
      def self.blank_day(day)
        gliders = Schedule.managed_gliders
        schedules = []
        gliders.each do |glider|
          sched = Schedule.new
          sched.glider = glider
          sched.day = day
          schedules.push(sched)
        end
        schedules
      end

      #Given two arrays A, B ... replace any elements in A if there is an
      #element in B with the same value for "glider"
      def self.merge_slots (a, b)

        #convert to hashes
        a_hash = a.map { |s| [s.glider, s] }.to_h
        b_hash = b.map { |s| [s.glider, s] }.to_h

        #replace
        b_hash.each_key {|k| a_hash[k] = b_hash[k]}

        #back to an aray
        a_hash.values

      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController


  def index
    if params[:q].present?
      date = Date.strptime(params[:q], '%Y-%m-%d')
      @schedules  = Schedule.schedule_for_day(date)
    else
      @schedules = Schedule.schedule_for_day(Date.current)
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    sched_params = params.require(:schedule).permit(Schedule.managed_time_slots)


##
#      :s0800, :s0830, :s0900, :s0930, :s1000, :s1030, :s1100, :s1130, :s1200,
#      :s1230, :s1300, :s1330, :s1400, :s1430, :s1500, :s1530, :s1600, :s1630
#      )


    @schedule.update(sched_params)
    redirect_to schedule_url_for(@schedule)
  end


  def new
    @schedule = Schedule.new(day: params[:new_schedule_date], glider: params[:new_schedule_glider])
  end

  def create
    sched_params = params.require(:schedule).permit(
      :day, :glider,
      :s0800, :s0830, :s0900, :s0930, :s1000, :s1030, :s1100, :s1130, :s1200,
      :s1230, :s1300, :s1330, :s1400, :s1430, :s1500, :s1530, :s1600, :s1630
      )
    @schedule = Schedule.new(sched_params)
    @schedule.save
    redirect_to schedule_url_for(@schedule)
  end

  private

    #After update we want to return to the index page but show reservations for the
    #date of the glider schedule we updated.  Modify schedules_url to include arugemnt for the
    #specific day to be used for the index action above
    def schedule_url_for(schedule)
      #{}"#{schedules_url}?utf8=✓&q=#{schedule.day.to_s}"
      "#{schedules_url}?q=#{schedule.day.to_s}"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
require 'uri'
module SchedulesHelper

  def link_to_edit_or_new(sched)
    if sched.id
      link_to "Reserve", edit_schedule_path(sched)
    else
      link_to "Reserve", new_schedule_path(:new_schedule_date => sched.day, :new_schedule_glider => sched.glider)
    end
  end

  #Create and return 2D array of values from list of schedule objects
  def array_from_schedule(scheds)
      scheds.map { |s| [
        s.s0800, s.s0830, s.s0900, s.s0930, s.s1000, s.s1030, s.s1100, s.s1130, s.s1200, s.s1230,
        s.s1300, s.s1330, s.s1400, s.s1430, s.s1500, s.s1530, s.s1600, s.s1630 ] }
  end

  def time_for_index(index)
    t_column = [
      "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30",
      "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30"]
    t_column[index]
  end

    #After update we want to return to the index page but show reservations for the
    #date of the glider schedule we updated.  Modify schedules_url to include arugemnt for the
    #specific day to be used for the index action above
    def schedule_url_for(schedule)
     # "#{schedules_url}?utf8=✓&q=#{schedule.day.to_s}"
        "#{schedules_url}?q=#{schedule.day.to_s}"
    end

    ##
    #Return a Rails Boostrap datepicker
    def date_picker
      text_field_tag(:q, value = @schedules.first.day, "data-provide" => 'datepicker', "data-date-format" => 'yyyy-mm-dd', "data-date-today-btn" => "linked", "data-date-today-highlight" => true, "data-date-days-of-week-highlighted" => [0,6], "data-date-disable-entry" => true, "data-date-orientation" => "bottom-right" )
    end

end

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2022 Envision Development LLC
  </p>
</footer>

app/views/layouts/_header.html.erb
  	<header id="page-header"">
  	  <h1>Highflights Soaring Club</h1>
  	</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li>
        <%= link_to "Today's Reservations", schedules_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HFSC Reservations</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<%= render "layouts/header" %>

	<%= render "layouts/sidebar" %>

    <%= yield %>

	<%= render "layouts/footer" %>

  </body>
</html>

app/views/schedules/_slots.html.erb
  <p>
    <%= f.label "8:00 "  %>  
    <%= f.text_field :s0800 %>
  </p>
  <p>
    <%= f.label "8:30 " %>
    <%= f.text_field :s0830 %>
  </p>
  <p>
    <%= f.label "9:00" %>
    <%= f.text_field :s0900 %>
   </p>
  <p>
    <%= f.label "9:30" %>
    <%= f.text_field :s0930 %>
  </p>
  <p>
    <%= f.label "10:00" %>
    <%= f.text_field :s1000 %>
  </p>
  <p>
    <%= f.label "10:30" %>
    <%= f.text_field :s1030 %>
  </p>
  <p>
    <%= f.label "11:00"  %>
    <%= f.text_field :s1100 %>
  </p>
  <p>
    <%= f.label "11:30" %>
    <%= f.text_field :s1130 %>
  </p>
  <p>
    <%= f.label "12:00" %>
    <%= f.text_field :s1200 %>
  </p>
  <p>
    <%= f.label "12:30" %>
    <%= f.text_field :s1230 %>
  </p>
  <p>
    <%= f.label "13:00" %>
    <%= f.text_field :s1300 %>
  </p>
  <p>
    <%= f.label "13:30" %>
    <%= f.text_field :s1330 %>
  </p>
    <p>
    <%= f.label "14:00"  %>
    <%= f.text_field :s1400 %>
  </p>
  <p>
    <%= f.label "14:30" %>
    <%= f.text_field :s1430 %>
  </p>
  <p>
    <%= f.label "15:00" %>
    <%= f.text_field :s1500 %>
  </p>
  <p>
    <%= f.label "15:30" %>
    <%= f.text_field :s1530 %>
  </p>
  <p>
    <%= f.label "16:00" %>
    <%= f.text_field :s1600 %>
  </p>
  <p>
    <%= f.label "16:30" %>
    <%= f.text_field :s1630 %>
  </p>

app/views/schedules/edit.html.erb
<h2>Editing Schedule: <%= @schedule.glider %></h2>
<h3><%= @schedule.day.strftime("%A, %B %d") %></h3>

<%= form_for(@schedule) do |f| %>
  <%= render :partial => 'slots', locals: {f: f} %>
  <p>
    <%= f.submit %>
    <%= link_to "Cancel", schedule_url_for(@schedule) %>
  </p>
<% end %>

app/views/schedules/index.html.erb
<h1>Glider Reservations</h1>
<h2><%= @schedules.first.day.to_formatted_s(:long) %></h2>

<table class= "schedules_table">
  <tr>
  	<th>Time</th>
    <% @schedules.each_with_index do |sched, i| %>
      <th><%=sched.glider%>  <%= link_to_edit_or_new(sched) %></th>
    <% end %>
  </tr>

<% array_from_schedule(@schedules).transpose.each_with_index do |row, i| %>

     <tr>
       <td><%= time_for_index(i) %></td>
       <% row.each do |cell| %>
          <td><%= cell %></td>
       <% end %>
     </tr>

<% end %>
</table>

<p>
<%= form_tag(schedules_url, method: "get") do %>
  <%= label_tag(:q, "Schedule for:") %>
  <%= date_picker %>
  <%= submit_tag("Change Date") %>
<% end %>
</p>

app/views/schedules/new.html.erb
<h2>Editing Schedule: <%= @schedule.glider %></h2>
<h3><%= @schedule.day.strftime("%A, %B %d") %></h3>

<%= form_for(@schedule) do |f| %>
  <%= render :partial => 'slots', locals: {f: f} %>

  <p>
    <%= f.hidden_field :day  %>
    <%= f.hidden_field :glider %>
  </p>

  <p>
    <%= f.submit %>
    <%= link_to "Cancel", schedule_url_for(@schedule) %>
  </p>
<% end %>